version: "3"

services:

  database:
    container_name: incremental_backups
    build:
      context: Server_incremental_log
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - database:/var/lib/mysql
      - ./incremental-logs:/Volumes/incremental

volumes:
  database:
