version: "3"

services:

  database:
    container_name: incremental_backups
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - database:/var/lib/mysql
      - ./Server/Configurations/enable-binary-log.cnf:/etc/mysql/conf.d/enable-binary-log.cnf
      - ./Binary-logs:/var/log/mysql/:rw
    restart: always

volumes:
  database:
